before_install:
  # init xvfb
  # http://docs.travis-ci.com/user/gui-and-headless-browsers/
  - "export DISPLAY=:99.0 && sh -e /etc/init.d/xvfb start"
branches:
  only:
  - alpha
  - beta
  - master
language:
  - c
node_js:
  - '0.10'
script:
  # test usage example
  - eval "$(curl -fLSs http://kaizhu256.github.io/node-install/node-install.sh)"
  # add $HOME/bin to $PATH
  export PATH=$HOME/bin:$PATH
  # test nodejs
  node -e "console.log(process.version)"
  # cleanup nodejs
  rm -r $HOME/bin
  # install nodejs
  - /bin/sh ./node-install.sh
